package me.timothy.bots.database;

import java.sql.Timestamp;
import java.util.List;

import me.timothy.bots.models.RedFlagUserHistoryLink;

/**
 * Maps red flag user history links to/from the database
 * 
 * @author Timothy
 */
public interface RedFlagUserHistoryLinkMapping extends ObjectMapping<RedFlagUserHistoryLink> {
	/**
	 * Fetch the link with the given id
	 * @param id id of the row to fetch
	 */
	public RedFlagUserHistoryLink fetchByID(int id);

	/**
	 * Fetch any links for the given report that occurred at the given timestamp
	 * @param reportId the report
	 * @param timestamp the timestamp
	 * @return links for that report at that time
	 */
	public List<RedFlagUserHistoryLink> fetchAtTimestamp(int reportId, Timestamp timestamp);
	
	/**
	 * Fetch the next link that is strictly after the given timestamp
	 * @param reportId the report you are considering
	 * @param timestamp the timestamp
	 * @return the next link after that timestamp
	 */
	public RedFlagUserHistoryLink fetchNextAfter(int reportId, Timestamp timestamp);
	
	/**
	 * Delete any links that were generated by the given report
	 * @param reportId the id of the report whose links should be purged
	 */
	public void deleteByReportID(int reportId);
}
